### ISSUE TITLE
404 page is wrong

### ISSUE THREAD

**Issue by Justme0** [kenmux/kenmux.github.io#1]
Hello! I found the 404 page of your theme is in disorder.
e.g.  https://xiwan.io/111111

**Comment by kenmux** [comment]
@Justme0, thanks for your info. I'll look into this issue later.

**Comment by kenmux** [comment]
@Justme0, now it's [okay](https://github.com/kenmux/kenmux.github.io/commit/455e3ea416e517cfacf224e7d8394064b8924d86)!
Do report if any issues, thanks again!
